# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'iOS_Exam' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for iOS_Exam
  pod 'Alamofire'

  target 'iOS_ExamTests' do
      inherit! :search_paths
      pod 'Alamofire'
      pod 'Quick'
      pod 'Mockingjay'
  end
end
